version: "3.8"
services:
  redis:
    image: ${REGISTRY}/redis
    deploy:
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 2G
      replicas: ${REDIS_REPLICAS}
  plat5:
    image: ${IMAGE_NAME}
    labels:
      - io.portainer.accesscontrol.public
    environment:
      - R_HOST=rscript
    working_dir: /var/www/html/
    ports:
      - target: 8080
        published: 80
        mode: host
      - target: 8443
        published: 443
        mode: host
      - target: 8888
        published: 8888
        mode: host
    deploy:
      placement:
        max_replicas_per_node: 1
      mode: replicated
      replicas: ${PLAT_REPLICAS}
      resources:
        limits:
          memory: 4G
    volumes:
      - plat_storage:/var/www/html/storage/app
      - plat_log:/var/www/html/storage/logs
    configs:
      - source: supervisord_config
        target: /etc/supervisor/conf.d/supervisord.conf
        gid: "502"
        uid: "501"
      - source: plat_env
        target: /var/www/html/.env
        uid: "501"
        gid: "502"
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
        gid: "502"
        uid: "501"
        mode: 0440
      - source: nginx_ssl_crt
        target: /etc/nginx/ssl/nginx.crt
        gid: "502"
        uid: "501"
      - source: nginx_ssl_key
        target: /etc/nginx/ssl/nginx.key
        gid: "502"
        uid: "501"
      - source: php_config
        target: /usr/local/etc/php/php.ini
        gid: "502"
        uid: "501"
      - source: phpfpm_config
        target: /usr/local/etc/php-fpm.d/www.conf
        gid: "502"
        uid: "501"
    secrets:
      - source: nginx_htpasswd
        target: /etc/nginx/htpasswd
        gid: "502"
        uid: "501"
      - source: code_server_config
        target: /var/www/.config/code-server/config.yaml
        gid: "502"
        uid: "501"
        mode: 0755
volumes:
  plat_storage:
    driver_opts:
      type: "cifs"
      o: "addr=${PLAT_STORAGE_HOST},username=${PLAT_STORAGE_USER},password=${PLAT_STORAGE_PW},file_mode=0777,dir_mode=0777"
      device: "//${PLAT_STORAGE_HOST}/${PLAT_STORAGE_PATH}/storage/app"
  plat_log:
    driver_opts:
      type: "cifs"
      o: "addr=${PLAT_STORAGE_HOST},username=${PLAT_STORAGE_USER},password=${PLAT_STORAGE_PW},file_mode=0777,dir_mode=0777"
      device: "//${PLAT_STORAGE_HOST}/${PLAT_STORAGE_PATH}/storage/logs"
configs:
  supervisord_config:
    name: ${ENV_TYPE}_${PROJECT_KEY}_supervisord_config_${CONFIG_VERSION}
    file: ./build/config/supervisor/conf.d/supervisord.conf
  plat_env:
    name: ${ENV_TYPE}_${PROJECT_KEY}_plat_env_${CONFIG_VERSION}
    file: ./build/config/${PLAT_ENV}
  nginx_conf:
    name: ${ENV_TYPE}_${PROJECT_KEY}_nginx_conf_${CONFIG_VERSION}
    file: ./build/config/nginx-ssl.conf
  nginx_ssl_crt:
    name: ${ENV_TYPE}_${PROJECT_KEY}_nginx_ssl_crt_${CONFIG_VERSION}
    file: ./build/config/ssl/nginx.crt
  nginx_ssl_key:
    name: ${ENV_TYPE}_${PROJECT_KEY}_nginx_ssl_key_${CONFIG_VERSION}
    file: ./build/config/ssl/nginx.key
  php_config:
    name: ${ENV_TYPE}_${PROJECT_KEY}_php_config_${CONFIG_VERSION}
    file: ./build/config/php.ini-${PLAT_ENV}
  phpfpm_config:
    name: ${ENV_TYPE}_${PROJECT_KEY}_phpfpm_config_${CONFIG_VERSION}
    file: ./build/config/www.conf
secrets:
  nginx_htpasswd:
    name: ${ENV_TYPE}_${PROJECT_KEY}_nginx_htpasswd_${CONFIG_VERSION}
    file: ./build/config/htpasswd
  code_server_config:
    name: ${ENV_TYPE}_${PROJECT_KEY}_code_server_config_${CONFIG_VERSION}
    file: ./build/.config/code-server/config.yaml
